#!/bin/sh
#
# Runs the `vmc` application as a daemon, compiled from the latest code.
#
# First the JAR is built with Maven, and then it's run separately.
# It's also possible to run the code directory from within Maven, using
# the Exec plugin. But that loads more classes and uses more memory.

cd "$(dirname $0)" || exit

# Workaround for unsafe memory access on JDK 24 by Maven 3.9.11 and lower.
# Once fixed in a new Maven release, this option can be removed.
# https://github.com/apache/maven/issues/10312
export MAVEN_OPTS="--sun-misc-unsafe-memory-access=allow"

echo "Compiling and installing markdown-curator..."
mvn -f ../markdown-curator/pom.xml -q -B clean install -DskipTests

echo "Compiling and packaging vmc..."
mvn -q -B clean package

echo "Executing vmc..."
java -Xmx128m -jar target/vmc-1.0.0-SNAPSHOT.jar "$@"
